service: cloudlrs
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  timeout: 10
  memorySize: 128
  # default stage is dev
  stage: <serverless/dev/prod/test>

functions:
  ingest:
    handler: index.handler
    description: 'LRS ingest function deployed via serverless'
    role: arn:aws:iam::1234567890:role/abcdefgxyz
    versionFunctions: false
